version: '3.8'

services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    networks:
      - backend

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: testUser
      POSTGRES_PASSWORD: tEstpAsswOrd!@2
      POSTGRES_DB: testDb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    networks:
      - backend

  user-service:
    build:
      context: ./user-service
    environment:
      - NATS_URL=nats://nats:4222
      - DATABASE_URL=postgres://testUser:tEstpAsswOrd!@2@postgres:5432/testDb?sslmode=disable&search_path=user_service
      - DB_PROVIDER=postgres
    depends_on:
      - nats
      - postgres
    ports:
      - "8080:8080"
    networks:
      - backend

  transactions-service:
    build:
      context: ./transactions-service
    environment:
      - NATS_URL=nats://nats:4222
      - DATABASE_URL=postgres://testUser:tEstpAsswOrd!@2@postgres:5432/testDb?sslmode=disable&search_path=transactions_service
      - DB_PROVIDER=postgres
    depends_on:
      - nats
      - postgres
    ports:
      - "8081:8081"
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data:
