basePath: /api/v1
definitions:
  requests.AddMoneyRequest:
    properties:
      amount:
        type: number
      user_id:
        type: integer
    type: object
  requests.TransferMoneyRequest:
    properties:
      amount_to_transfer:
        type: number
      from_user_id:
        type: integer
      to_user_id:
        type: integer
    type: object
  responses.AddMoneyResponse:
    properties:
      balance:
        type: number
      status:
        type: string
    type: object
  responses.BaseResponse:
    properties:
      message:
        type: string
      status:
        type: string
    type: object
host: localhost:8081
info:
  contact: {}
  description: This is a sample Transaction Service for a digital wallet.
  title: Golang Digital Wallet Transaction Service
  version: "1.0"
paths:
  /addMoney:
    post:
      consumes:
      - application/json
      description: Add a specified amount of money to a user's account balance
      parameters:
      - description: Add Money Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/requests.AddMoneyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.AddMoneyResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.BaseResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.BaseResponse'
      summary: Add money to a user's account
      tags:
      - transactions
  /transferMoney:
    post:
      consumes:
      - application/json
      description: Transfer a specified amount of money from one user's account to
        another
      parameters:
      - description: Transfer Money Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/requests.TransferMoneyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.BaseResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.BaseResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.BaseResponse'
      summary: Transfer money between two users
      tags:
      - transactions
swagger: "2.0"
